version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.32
    ports:
      - "4466:4466"
    depends_on:
      - mongo-db
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            rawAccess: true
            connector: mongo
            uri: mongodb://prisma:prisma@mongo-db
  mongo-db:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
      - ./data:/var/lib/mongo